### ISSUE TITLE
Failed to build with git-master of wlroots

### ISSUE THREAD

**Issue by yan12125** [WayfireWM/wayfire#229]
```
FAILED: src/25a6634@@wayfire@exe/core_core.cpp.o
c++ -Isrc/25a6634@@wayfire@exe -Isrc -I../src -I. -I../ -I../src/api -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libevdev-1.0/ -I/usr/include/wayfire -I/usr/include/libpng16 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -DWLR_USE_UNSTABLE -Wno-unused-parameter -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIE -MD -MQ 'src/25a6634@@wayfire@exe/core_core.cpp.o' -MF 'src/25a6634@@wayfire@exe/core_core.cpp.o.d' -o 'src/25a6634@@wayfire@exe/core_core.cpp.o' -c ../src/core/core.cpp
../src/core/core.cpp:4:10: fatal error: wlr/types/wlr_screenshooter.h: No such file or directory
 #include <wlr/types/wlr_screenshooter.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Built with https://github.com/swaywm/wlroots/commit/3dec88e4555ee5fd95ffd69133623816cb0c25c4. From what I can tell `wlr_screenshooter.h` is removed.

**Comment by ammen99** [comment]
Oh yeah, currently I build with wlroots 0.6. I'll update soon.
