### ISSUE TITLE
Build of Wayfire 0.10.1-1 from AUR Fails

### ISSUE THREAD

**Issue by octoamit** [WayfireWM/wayfire#2921]
**Describe the bug**
When updating wayfire to 0.10.1-1 from the AUR, the build process fails with "fatal error: wayfire/nonstd/safe-list.hpp: No such file or directory". Building the release from source results in the same fatal error, so the issue may not be exclusive to the AUR.

**To Reproduce**
1. Attempt to upgrade wayfire from AUR, e.g. ```yay -S wayfire```
2. The build process fails with "fatal error: wayfire/nonstd/safe-list.hpp: No such file or directory".

**Expected behavior**
The package updates to 0.10.1-1.

**Screenshots or stacktrace**
```
...
In file included from ../wayfire-0.10.1/src/core/output-layout.cpp:11:
../wayfire-0.10.1/src/core/../output/output-impl.hpp:11:10: fatal error: wayfire/nonstd/safe-list.hpp: No such file or directory
   11 | #include <wayfire/nonstd/safe-list.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[99/500] Compiling C++ object src/liblibwayfire.a.p/core_plugin-loader.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: wayfire-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
wayfire - exit status 4
```

**Wayfire version**
[Wayfire 0.10.1-1](https://aur.archlinux.org/packages/wayfire)
This is the _regular_ "wayfire" package on the AUR... not the "wayfire-git" package.

**Comment by ammen99** [comment]
@octoamit the missing header is part of `wf-config` since the 0.10.0 release. Are you sure you have installed the newest wf-config? I would also check in `/usr/include/wayfire/nonstd` to verify that the `safe-list.hpp` file is present there. If it is not, then that would indicate that the wf-config installation is broken/incomplete.

**Comment by octoamit** [comment]
I do have the latest release of wf-config, but I did not have `safe-list.hpp` in `/usr/include/wayfire/nonstd`. 

I reinstalled wf-config and did a clean build. After that I did have `safe-list.hpp` in `/usr/include/wayfire/nonstd` and wayfire updated normally. 

I will close this issue and update my comment on the AUR. Thank you so much for your help!
