### ISSUE TITLE
[0.10.0] Fails to find <GLES2/gl2.h> under non-default prefix

### ISSUE THREAD

**Issue by jbeich** [WayfireWM/wayfire#2800]
**Describe the bug**
Regressed by #2591: CFLAGS from `dependencies` are no longer passed. Affects [FreeBSD](https://wiki.freebsd.org/WarnerLosh/UsrLocal#Include_paths), other BSDs and maybe even Nix due to using different prefix for each package. 

**To Reproduce**
1. Install GLESv2 from libglvnd (or Mesa) outside of `/usr` and `/usr/local` thus not part of default C compiler search path
2. Pass `PKG_CONFIG_PATH` pointing to non-default GLESv2 install
3. Build Wayfire
4. Bump into the error

**Expected behavior**
To build fine.

**Screenshots or stacktrace**
```c
$ cc --version
FreeBSD clang version 19.1.7 (https://github.com/llvm/llvm-project.git llvmorg-19.1.7-0-gcd708029e0b2)
Target: x86_64-unknown-freebsd13.5
Thread model: posix
InstalledDir: /usr/bin

$ export PKG_CONFIG_PATH=/libglvnd_prefix/lib/pkgconfig
$ pkg-config --cflags libglvnd
-I/libglvnd_prefix/include

$ meson setup /tmp/wayfire_build
$ meson compile -C /tmp/wayfire_build
[...]
FAILED: plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o
cc -Iplugins/wobbly/libwobbly-c-model.a.p -Iplugins/wobbly -I../plugins/wobbly -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -DWLR_USE_UNSTABLE -DHAVE_LIBINPUT_3FG_DRAG=1 -DWF_USE_CONFIG_H -fPIC -MD -MQ plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o -MF plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o.d -o plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o -c ../plugins/wobbly/wobbly.c
In file included from ../plugins/wobbly/wobbly.c:38:
../plugins/wobbly/wobbly.h:10:10: fatal error: 'GLES2/gl2.h' file not found
   10 | #include <GLES2/gl2.h>
      |          ^~~~~~~~~~~~~
1 error generated.
```

**Wayfire version**
0.10.0

**Comment by ammen99** [comment]
Ah, I see, we do not specify the correct deps for the wobbly.c file.

**Comment by jbeich** [comment]
For reference, here's how compiler flags look like **after** the fix.
```
$ cd /tmp/wayfire_build
$ rm plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o
$ ninja -v plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o
[1/1] cc -Iplugins/wobbly/libwobbly-c-model.a.p -Iplugins/wobbly -I../../mnt/plugins/wobbly -I/usr/local/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -DWLR_USE_UNSTABLE -DHAVE_LIBINPUT_3FG_DRAG=1 -DWF_USE_CONFIG_H -fPIC -MD -MQ plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o -MF plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o.d -o plugins/wobbly/libwobbly-c-model.a.p/wobbly.c.o -c ../../mnt/plugins/wobbly/wobbly.c
```
