### PR TITLE
Fixes #2582

### LINKED ISSUE #2582: blur plugin uses std::list but does not include <list>
**Describe the bug**
`plugins/blur/blur.cpp` references `std::list` but `<list>` is not included anywhere in the headers it imports.

**To Reproduce**
1. Attempt to build the project
2. Error occurs when building `plugins/blur/libblur.so.p/blur.cpp.o`

**Expected behavior**
Project should build cleanly.

**Screenshots or stacktrace**
```
[337/482] Compiling C++ object plugins/blur/libblur.so.p/blur.cpp.o
FAILED: plugins/blur/libblur.so.p/blur.cpp.o
c++ -Iplugins/blur/libblur.so.p -Iplugins/blur -I../plugins/blur -I../src/api -I. -I.. -I/usr/include/wlroots-0.18 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -flto=auto -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O3 '-DWAYFIRE_VERSION="0.10.0"' -DWLR_USE_UNSTABLE -fno-gnu-unique -Wno-unused-parameter -DWF_USE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/wayfire-hidpi-xprop-git/src=/usr/src/debug/wayfire-hidpi-xprop-git -flto=auto -fPIC -MD -MQ plugins/blur/libblur.so.p/blur.cpp.o -MF plugins/blur/libblur.so.p/blur.cpp.o.d -o plugins/blur/libblur.so.p/blur.cpp.o -c ../plugins/blur/blur.cpp
../plugins/blur/blur.cpp:79:10: error: ‘list’ in namespace ‘std’ does not name a template type
   79 |     std::list<saved_pixels_t> saved_pixels;
      |          ^~~~
../plugins/blur/blur.cpp:15:1: note: ‘std::list’ is defined in header ‘<list>’; this is probably fixable by adding ‘#include <list>’
   14 | #include "blur.hpp"
  +++ |+#include <list>
   15 | #include "wayfire/core.hpp"
../plugins/blur/blur.cpp: In destructor ‘virtual wf::scene::blur_node_t::~blur_node_t()’:
../plugins/blur/blur.cpp:56:29: error: ‘saved_pixels’ was not declared in this scope; did you mean ‘saved_pixels_t’?
   56 |         for (auto& buffer : saved_pixels)
      |                             ^~~~~~~~~~~~
      |                             saved_pixels_t
../plugins/blur/blur.cpp: In member function ‘wf::scene::blur_node_t::saved_pixels_t* wf::scene::blur_node_t::acquire_saved_pixel_buffer()’:
../plugins/blur/blur.cpp:82:32: error: ‘saved_pixels’ was not declared in this scope; did you mean ‘saved_pixels_t’?
   82 |         auto it = std::find_if(saved_pixels.begin(), saved_pixels.end(),
      |                                ^~~~~~~~~~~~
      |                                saved_pixels_t
```

**Wayfire version**
wayfire-git v0.9.0-44-gc171f623

### PR DESCRIPTION
**Pull request by marcusbritanicus**

### CODE REVIEW

**Comment by marcusbritanicus** [comment]
@ammen99 While this PR mitigates the issues faced in #2582, I think the offending commit was [wf-config#75](https://github.com/WayfireWM/wf-config/pull/75/files#diff-3dcb96ef7a750cdf567c7e762ce0302208c15b479199b9fda8a7d6c33e91f5e2L4).

I will leave the decision up to you.

**Comment by ammen99** [comment]
Thanks! I actually even have a fix for this in my next PR but let's first merge this one.
