### ISSUE TITLE
Resize sometimes grows/shrinks windows from the wrong side

### ISSUE THREAD

**Issue by Soapsuds** [WayfireWM/wayfire#1053]
**Describe the bug**
When using the hotkey to resize the window isn't always grabbed from the correct side. eg. starting the resize on the left side of the window and dragging left will shrink it the from the right side instead of enlarging it. Resizing from the left side again allows it to enlarge as expected, however, after resizing from the left starting a resize from the right will again produce the incorrect behavior until grabbed from the right side a second time.

**To Reproduce**
1. open a new window
2. resize to the right by mousing over and activating the shortcut (default super+rightclick)
3. now resize from the left
4. resize has shrunk the window from the right

**Expected behavior**
Resize should always resize from the expected side

**Screenshots or stacktrace**
https://user-images.githubusercontent.com/3620789/105172928-8b85b500-5add-11eb-8756-a5a9556229b5.mp4

**Wayfire version**
git 98c09c7a719a86b2d676c39978e036ae54f414db

**Comment by chaoskagami** [comment]
I noticed this too with my latest recompile, and it's really inconvenient.

**Comment by ammen99** [comment]
Please test #1057

**Comment by chaoskagami** [comment]
Recompiling now to test. I have to wait for something I was doing to complete before I can restart wayland, so it'll be a bit before I can report back.

**Comment by chaoskagami** [comment]
Ehh. I can't compile current git master in its current state due to a compilation error in `grid`. More specifically, GCC really doesn't like the `animation_type.value()` calls. Reverting f9cdd8f884027423679d75189560be533c50fa59 (aside from the submodule update) fixes the compilation error for the moment, so I had to do that to test. I'll report back after I restart wayfire.

**Comment by chaoskagami** [comment]
Yup, that patch seems to have fixed it.

**Comment by ammen99** [comment]
> Ehh. I can't compile current git master in its current state due to a compilation error in `grid`. More specifically, GCC really doesn't like the `animation_type.value()` calls, not sure why. Reverting [f9cdd8f](https://github.com/WayfireWM/wayfire/commit/f9cdd8f884027423679d75189560be533c50fa59) (aside from the submodule update) fixes the compilation error for the moment, so I had to do that to test. I'll report back after I restart wayfire.

You probably haven't updated wf-config

**Comment by chaoskagami** [comment]
>You probably haven't updated wf-config

Ah, live ebuilds. The bane of my existence when they don't pick up related changes...that was it, thanks. I figured it was something stupid, hence why I didn't immediately open a report until I looked into whether it was my fault. Anyways, thanks for saving me some time.
