### ISSUE TITLE
wayfire does not build with wlroots 0.1.0 

### ISSUE THREAD

**Issue by colemickens** [WayfireWM/wayfire#95]
I'm getting (at least) this as a build error:
```
../src/core/seat/keyboard.cpp: In member function 'bool input_manager::handle_keyboard_key(uint32_t, uint32_t)':
../src/core/seat/keyboard.cpp:202:29: error: 'wlr_multi_get_session' was not declared in this scope
         if (check_vt_switch(wlr_multi_get_session(core->backend), key, get_modifiers()))
                             ^~~~~~~~~~~~~~~~~~~~~
../src/core/seat/keyboard.cpp:202:29: note: suggested alternative: 'wlr_backend_get_session'
         if (check_vt_switch(wlr_multi_get_session(core->backend), key, get_modifiers()))
                             ^~~~~~~~~~~~~~~~~~~~~
                             wlr_backend_get_session
../src/core/seat/keyboard.cpp: At global scope:
../src/core/seat/keyboard.cpp:129:13: warning: 'bool check_vt_switch(wlr_session*, uint32_t, uint32_t)' defined but not used [-Wunused-function]
 static bool check_vt_switch(wlr_session *session, uint32_t key, uint32_t mods)
             ^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

wlroots 0.1.0 was cut with the last couple weeks, the change that introduced this build error was merged prior to that. There may be other changes necessary.

https://github.com/swaywm/wlroots/pull/1262

**Comment by ammen99** [comment]
Duplicate of #91
